#Set of URL mappings that do a little bit of overhead work. Most of the data generation
#is done in the GenerateData file (which should probably be run offline since the professor
#data should be static).

from flask import Flask, render_template, request, url_for, Markup

app = Flask(__name__)
app.config['DEBUG'] = True


uw_flow_url = 'https://uwflow.com/course/'

instructorList = list()
instructorMapping = dict()
loaded = False

#Reads the pre-generated files containing the list of professors mapped to a list of courses,
#that was generated by the GenerateData.py file.
def loadData():
	global instructorMapping
	f = open('ClassesMapped', 'r')
	lines = f.readlines()
	for i in lines:
		part = i.partition('(')[0].rstrip()
		instructorMapping[part] = '(' + i.partition('(')[2]
		instructorList.append(part)

def convertName(name):
	return name.replace(',', ", ")


@app.route('/')
def main():
	global loaded
	selectList = ""
	if not loaded:
		loadData()
		loaded = True
	for i in instructorList:
		selectList+=render_template("fe.html", name=convertName(i))
	return render_template("main.html", content=selectList)

@app.route('/search')
def search():
	global instructorMapping
	name = request.args['prof'].split(',')
	firstName = name[1].lstrip()
	lastName = name[0]
	classes = instructorMapping[str(request.args['prof']).replace(', ', ',')].rstrip().replace('(', '').replace(')', '').split(' ')
	classString = ""
	for i in range(0, len(classes)/4):
		classString+= render_template("class.html", course=classes[i*4], room=classes[i*4 + 1], time = classes[i*4 + 2] + ' ' + classes[i*4 + 3], courseLower = classes[i*4].lower())
	return render_template("search.html", firstName = firstName, lastName = lastName, content = classString)